version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./tmp:/tmp  # For temporary files during testing
    environment:
      - FLASK_ENV=production
    restart: unless-stopped

  redis:  # For caching model information
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data: