name: Test Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
          
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r website/requirements.txt
        pip install pytest pytest-cov
        
    - name: Run tests
      run: |
        cd website
        python -m pytest tests/ --cov=. --cov-report=xml
        
    - name: Upload coverage
      uses: codecov/codecov-action@v2
      with:
        file: ./website/coverage.xml
        fail_ci_if_error: true